classDiagram
    Association <-- association
    Inheritance <|-- inheritance
    Realization <|.. realisation
    Dependency <.. dependency
    Aggregation o-- aggregation
    Composition *-- composition
    LinkSolid -- linksolid
    LinkDashed .. linkdashed